version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    labels:
    - enhancement
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: monthly
    labels:
    - enhancement