linters:
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - dupl
  - durationcheck
  - errcheck
  - errorlint
  - exhaustive
  - exportloopref
  - forbidigo
  - gci
  - gocritic
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - goimports
  - golint
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
  - interfacer
  - makezero
  - misspell
  - noctx
  - nolintlint
  - prealloc
  - predeclared
  - revive
  - rowserrcheck
  - scopelint
  - sqlclosecheck
  - staticcheck
  - structcheck
  - stylecheck
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace
  disable:
  - exhaustivestruct
  - funlen
  - ifshort # FIXME re-enable when bugs in ifshort are fixed
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocyclo
  - godox
  - goheader
  - gomnd
  - lll
  - maligned
  - nakedret
  - nestif
  - nlreturn
  - paralleltest
  - testpackage
  - tparallel
  - wrapcheck
  - wsl

linters-settings:
  forbidigo:
    forbid:
    - ^fmt\.Print.*$
    - ^ioutil\.
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/twpayne/chezmoi
  misspell:
    locale: US

issues:
  exclude-rules:
  - linters:
    - goerr113
    text: "do not define dynamic errors, use wrapped static errors instead"
  - linters:
    - forbidigo
    - gosec
    path: ^internal/cmd/
  - linters:
    - gosec
    - scopelint
    path: "_test\\.go$"
