linters:
  enable-all: true
  disable:
    - goconst
    - gocyclo
    - lll
    - maligned

issues:
  exclude-rules:
    - linters:
        - gochecknoglobals
        - gochecknoinits
      path: cmd/
    - linters:
        - gochecknoglobals
      path: internal/
    - linters:
        - scopelint
      path: "_test\\.go"