linters:
  enable-all: true
  disable:
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - godox
    - lll
    - maligned
    - wsl

issues:
  exclude-rules:
    - linters:
        - dupl
      path: "secretgopass.go"
    - linters:
        - dupl
      path: "secretpass.go"
    - linters:
        - gochecknoglobals
        - gochecknoinits
      path: cmd/
    - linters:
        - gochecknoglobals
      path: internal/
    - linters:
        - scopelint
      path: "_test\\.go"