project_name: chezmoi

before:
  hooks:
  - go mod download

builds:
- id: chezmoi-cgo
  binary: chezmoi
  ldflags: "-s -w -X github.com/twpayne/chezmoi/cmd.VersionStr={{ .Version }} -X github.com/twpayne/chezmoi/cmd.Commit={{ .Commit }} -X github.com/twpayne/chezmoi/cmd.Date={{ .Date }}"
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
  - amd64
- id: chezmoi-nocgo
  binary: chezmoi
  env:
  - CGO_ENABLED=0
  ldflags: "-s -w -X github.com/twpayne/chezmoi/cmd.VersionStr={{ .Version }} -X github.com/twpayne/chezmoi/cmd.Commit={{ .Commit }} -X github.com/twpayne/chezmoi/cmd.Date={{ .Date }}"
  goos:
  - linux
  - darwin
  - freebsd
  - openbsd
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  - ppc64
  - ppc64le
  goarm:
  - ""
  ignore:
  - goos: darwin
    goarch: 386
  - goos: linux
    goarch: amd64
- id: chezmoi-cgo-snap
  binary: chezmoi
  flags:
  - -tags=snap
  ldflags: "-s -w -X github.com/twpayne/chezmoi/cmd.VersionStr={{ .Version }} -X github.com/twpayne/chezmoi/cmd.Commit={{ .Commit }} -X github.com/twpayne/chezmoi/cmd.Date={{ .Date }}"
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
  - amd64
- id: chezmoi-nocgo-snap
  binary: chezmoi
  flags:
  - -tags=snap
  ldflags: "-s -w -X github.com/twpayne/chezmoi/cmd.VersionStr={{ .Version }} -X github.com/twpayne/chezmoi/cmd.Commit={{ .Commit }} -X github.com/twpayne/chezmoi/cmd.Date={{ .Date }}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - 386
  - arm64

archives:
- builds:
  - chezmoi-cgo
  - chezmoi-nocgo
  files:
  - LICENSE
  - README.md
  - completions/*
  - docs/*
  replacements:
    386: i386
  format_overrides:
  - goos: windows
    format: zip

nfpms:
- builds:
  - chezmoi-cgo
  - chezmoi-nocgo
  vendor: "Tom Payne <twpayne@gmail.com>"
  homepage: "https://chezmoi.io/"
  maintainer: "Tom Payne <twpayne@gmail.com>"
  description: "Manage your dotfiles across multiple machines, securely."
  license: MIT
  formats:
  - deb
  - rpm
  dependencies:
  - git
  bindir: /usr/bin
  files:
    "completions/chezmoi-completion.bash": "/usr/share/bash-completion/completions/chezmoi"
    "completions/chezmoi.fish": "/usr/share/fish/completions/chezmoi.fish"
  overrides:
    deb:
      file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      replacements:
        386: i386
        arm: armel
      files:
        "completions/chezmoi.zsh": "/usr/share/zsh/vendor-completions/_chezmoi"
    rpm:
      file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
      replacements:
        amd64: x86_64
        386: i686
        arm: armhfp
        arm64: aarch64
      files:
        "completions/chezmoi.zsh": "/usr/share/zsh/functions/_chezmoi"

brews:
- github:
    owner: twpayne
    name: homebrew-taps
  commit_author:
    name: Tom Payne
    email: twpayne@gmail.com
  folder: Formula
  homepage: "https://chezmoi.io"
  install: |
    bin.install "chezmoi"
    bash_completion.install "completions/chezmoi-completion.bash"
    zsh_completion.install "completions/chezmoi.zsh" => "_chezmoi"
    fish_completion.install "completions/chezmoi.fish"
  description: "Manage your dotfiles across multiple machines, securely."

scoop:
  bucket:
    owner: twpayne
    name: scoop-bucket
  commit_author:
    name: Tom Payne
    email: twpayne@gmail.com
  homepage: "https://chezmoi.io"
  description: "Manage your dotfiles across multiple machines, securely."
  license: MIT

snapcrafts:
- builds:
  - chezmoi-cgo-snap
  - chezmoi-nocgo-snap
  summary: "Manage your dotfiles across multiple machines, securely."
  description: "Manage your dotfiles across multiple machines, securely."
  publish: true
  grade: stable
  confinement: classic
  # FIXME on 2020-02-06 the snapcraft store was automatically rejecting
  # generated snaps with the message:
  #   chezmoi-completion.bash does not exist lint-snap-v2_completer (chezmoi)
  # See, for example:
  # https://dashboard.snapcraft.io/snaps/chezmoi/revisions/123/
  # This might be related to the completer script being in a subdirectory.
  # For now, disable bash completion.
  # apps:
  #   chezmoi:
  #     completer: completions/chezmoi-completion.bash