language: go

os:
- linux
- osx

addons:
  apt:
    packages:
    - rpm
    - snapd

go:
- 1.13.x

env:
- GO111MODULE=on PATH=/snap/bin:$PATH

install:
- go mod download
- make install-tools

script:
- make all
- git diff --exit-code
- make format
- git diff --exit-code
- make test
- make lint
- go run . --version
- GOOS=windows go build .

sudo: false

deploy:
- provider: script
  skip_cleanup: true
  script: make release-setup-travis release
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
