language: go

addons:
  apt:
    packages:
    # needed for goreleaser/nfpm:
    - rpm

go:
  - 1.12.x

env:
  - GO111MODULE=on

script:
  - go test ./...
  - go test -cover -race ./...
  - go vet ./...

sudo: false

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
